Neos:
  Neos:
    modules:
      administration:
        submodules:
          nodetypes:
            label: 'Shel.NodeTypes.Analyzer:Main:module.label'
            controller: 'Shel\NodeTypes\Analyzer\Controller\NodeTypesController'
            description: 'Shel.NodeTypes.Analyzer:Main:module.description'
            icon: 'fas fa-sitemap'
            privilegeTarget: 'Shel.NodeTypes.Analyzer:Backend.Module.Administration.NodeTypes'
            additionalResources:
              javaScripts:
                - 'resource://Shel.NodeTypes.Analyzer/Public/Assets/main.bundle.js'
              styleSheets:
                - 'resource://Shel.NodeTypes.Analyzer/Public/Assets/extra-neos-wrapper.css'

    userInterface:
      translation:
        autoInclude:
          Shel.NodeTypes.Analyzer:
            - 'Main'
