name: Code Quality Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, '[0-9]+.[0-9]' ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '22'
    - run: yarn
    - run: yarn lint
