name: Code Quality Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '22'
    - run: yarn
    - run: yarn lint

  codestyle:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Add additional dependencies
        run: |
          composer require --no-update --no-interaction neos/contentgraph-doctrinedbaladapter:"~9.0.0"
          composer require --no-update --no-interaction league/csv:"~9.0"

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache
          key: dependencies-composer-${{ hashFiles('composer.json') }}

      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          php_version: 8.2
          version: 2

      - name: PHPStan
        uses: php-actions/phpstan@v3
        with:
          php_version: 8.2
          version: 2.1.17
          command: analyse
          path: 'Classes/'
